BlogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home_app.urls")),
    path('', include("account.urls")),
    path('articles/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('detail/<slug:slug>', views.article_detail, name='article_detail'),
    path('list', views.article_list, name= 'article_list'),
    path('category/<int:pk>', views.category_detail, name='category_detail'),
    path('search/', views.search, name='search_articles'),
    path('contactus/', views.contact_us, name='contact_us'),
    path('about/', views.about, name='about'),
    path('like/<slug:slug>/<int:pk>', views.like, name='like')

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify

# Create your models here.


class Category(models.Model):
    Title = models.CharField(max_length=50)
    Created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Title

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'


class ArticleManager(models.Manager):
    def counter(self):
        return len(self.all())

    def published(self):
        return self.filter(published=True)


class Article(models.Model):
    Author = models.ForeignKey(User, on_delete=models.CASCADE)
    Title = models.CharField(max_length=70,)
    category = models.ManyToManyField(Category)
    Body = models.TextField()
    Image = models.ImageField(upload_to='articles')
    Created = models.DateTimeField(auto_now_add=True)
    Updated = models.DateTimeField(auto_now=True)
    pub_date = models.DateField(default=timezone.now)
    published = models.BooleanField(default=True)
    objects = ArticleManager()
    slug = models.SlugField(null=True, blank=True, unique=True)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify(self.Title)
        super(Article, self).save()

    def __str__(self):
        return f"{self.Title} - {self.Body[:30]}"

    class Meta:
        ordering = ('-Created',)
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'



class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    parents = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body[:30]

    class Meta:
        verbose_name = 'کامنت'
        verbose_name_plural = 'کامنت ها'


class Message(models.Model):
    name = models.CharField(max_length=50)
    text = models.TextField()
    email = models.EmailField()
    age = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'پیام'
        verbose_name_plural = 'پیام ها'


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes', verbose_name='کاربر')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='likes', verbose_name='مقاله')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.article.Title}"

    class Meta:
        verbose_name = 'لایک'
        verbose_name_plural = 'لایک ها'
        ordering = ('-created',)

blog/forms.py
from django import forms
from .models import Message
from django.core.validators import ValidationError


class ContactUsForm(forms.Form):
    name = forms.CharField(max_length=10, label='your name')
    text = forms.CharField(max_length=10, label='your message')

    def clean(self):
        name = self.cleaned_data.get('name')
        text = self.cleaned_data.get('text')
        if name == text:
            raise ValidationError('name and text are same', code='name_text_same')


class MessageForm(forms.Form):
    name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Name'}))
    text = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Enter your message'}))
    age = forms.IntegerField()
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Email'}))

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Article, Category, Message, Like
from django.core.paginator import Paginator
from .forms import ContactUsForm, MessageForm

# Create your views here.


def article_detail(request, slug):
    article = get_object_or_404(Article, slug=slug)
    if request.user.is_authenticated:
        if request.user.likes.filter(article__slug=slug, user_id=request.user.id).exists():
            is_liked = True
        else:
            is_liked = False
    else:
        return render(request, 'blog/article-details.html', context={'article': article})

    return render(request, 'blog/article-details.html', context={'article': article, 'is_liked': is_liked})


def article_list(request):
    article_list = Article.objects.all()
    page_number = request.GET.get('page')
    paginator = Paginator(article_list, 1)
    page_list = paginator.get_page(page_number)
    return render(request, 'blog/article_list.html', context={'article_list': page_list})


def category_detail(request, pk):
    categories = get_object_or_404(Category, pk=pk)
    articles = categories.article_set.all()
    return render(request, 'blog/article_list.html', context={'article_list': articles})


def search(request):
    q = request.GET.get('q')
    articles = Article.objects.filter(Title__icontains=q)
    page_number = request.GET.get('page')
    paginator = Paginator(articles, 1)
    page_list = paginator.get_page(page_number)
    return render(request, 'blog/article_list.html', {'article_list': page_list})


def contact_us(request):
    if request.method == 'POST':
        form = MessageForm(data=request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            text = form.cleaned_data['text']
            email = form.cleaned_data['email']
            Message.objects.create(name=name, text=text, email=email)

    else:
        form = MessageForm()
    return render(request, 'blog/contact.html', {'form': form})


def like(request, slug, pk):
    if request.user.is_authenticated:
        try:
            like = Like.objects.get(article__slug=slug, user_id=request.user.id)
            like.delete()
        except:
            Like.objects.create(article_id=pk, user_id=request.user.id)

        return redirect("blog:article_detail", slug)
    else:
        return redirect("blog:article_detail", slug)



def about(request):
    return render(request, 'blog/about.html',)

blog/templates/blog/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="text-content">
                <h4>about us</h4>
                <h2>more about us!</h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>

    <!-- Banner Ends Here -->


    <section class="about-us">
      <div class="container">

        <div class="row">
          <div class="col-lg-12">
            <img src="{% static "images/about-us.jpg" %}" alt="about-us image">
            <p>Please tell your friends about TemplateMo website. Thank you. You can browse through different categories of templates such as <a rel="nofollow" href="https://templatemo.com/tag/business" target="_parent">business</a>, <a rel="nofollow" href="https://templatemo.com/tag/portfolio" target="_parent">portfolio</a>, <a rel="nofollow" href="https://templatemo.com/tag/restaurant" target="_parent">restaurant</a>, etc. Pellentesque quis luctus libero. Maecenas pretium molestie erat, ac tincidunt leo gravida ac. Cras ullamcorper eu ipsum eu sollicitudin. Fusce vitae commodo turpis. Integer ullamcorper purus nec justo mollis fermentum. Nunc imperdiet erat nec lacinia laoreet. <br><br>Maecenas faucibus ullamcorper felis vitae finibus. Nullam at quam ut lacus aliquam tempor vel sed ipsum. Donec pellentesque tincidunt imperdiet. Mauris sit amet justo vulputate, cursus massa congue, vestibulum odio. Aenean elit nunc, gravida in erat sit amet, feugiat viverra leo. Phasellus interdum, diam commodo egestas rhoncus, turpis nisi consectetur nibh, in vehicula eros orci vel neque.</p>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-6">
          <h4>Two-One Donec porttitor augue</h4>
          	<p>Quisque bibendum cursus viverra. Mauris at ex ipsum. Aenean condimentum urna nisl, eget interdum ante euismod vel. Aliquam at metus sit amet nunc dapibus posuere.</p>
          </div>
          <div class="col-lg-6">
          <h4>Two-Two Donec porttitor augue</h4>
          	<p>Maecenas et metus nisl. Morbi ac interdum metus. Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-4 col-md-6">
          <h4>1-03 Donec porttitor augue</h4>
          	<p>Quisque bibendum cursus viverra. Mauris at ex ipsum. Aenean condimentum urna nisl, eget interdum ante euismod vel. Aliquam at metus sit amet nunc dapibus posuere.</p>
          </div>
          <div class="col-lg-4 col-md-6">
          <h4>2-03 Donec porttitor augue</h4>
          	<p>Maecenas et metus nisl. Morbi ac interdum metus. Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
          </div>
          <div class="col-lg-4">
          <h4>3-03 Donec porttitor augue</h4>
          	<p>Maecenas et metus nisl. Morbi ac interdum metus. Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
          </div>
        </div>


        <div class="row">
          <div class="col-lg-3 col-md-6">
          <h4>01 Four Columns</h4>
          	<p>Mauris at ex ipsum. Aenean condimentum urna nisl, eget interdum ante euismod vel. Aliquam at metus sit amet nunc dapibus posuere.</p>
          </div>
          <div class="col-lg-3 col-md-6">
          <h4>02 Four Columns</h4>
          	<p>Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
          </div>
          <div class="col-lg-3 col-md-6">
          <h4>03 Four Columns</h4>
          	<p>Morbi ac interdum metus. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
          </div>
          <div class="col-lg-3 col-md-6">
          <h4>04 Four Columns</h4>
          	<p>Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-12">
            <ul class="social-icons">
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-behance"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>


      </div>
    </section>
{% endblock %}

blog/templates/blog/article-details.html
{% extends 'base.html' %}
{% load  static %}

{% block title %}
    {{ article.Title }}
{% endblock %}

{% block content %}


    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
        <section class="page-heading">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-content">
                            <h4>Post Details</h4>
                            <h2>Single blog post</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Banner Ends Here -->

    <section class="call-to-action">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="main-content">
                        <div class="row">
                            <div class="col-lg-8">
                                <span>Stand Blog HTML5 Template</span>
                                <h4>{{ article.Title }}</h4>
                            </div>
                            <div class="col-lg-4">
                                <div class="main-button">
                                    <a rel="nofollow" href="https://templatemo.com/tm-551-stand-blog" target="_parent">Download
                                        Now!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="blog-posts grid-system">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="all-blog-posts">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="blog-post">
                                    <div class="blog-thumb">
                                        <img src="{{  url }}" alt="">
                                    </div>
                                    <div class="down-content">
                                        <span>{{ article.category }}</span>
                                        <a href="article-details.html"><h4>{{ article.Title }}</h4></a>
                                        <ul class="post-info">
                                            <li><a href="#">{{ article.Author }}</a></li>
                                            <li><a href="#">{{ article.Created }}</a></li>
                                            <li><a href="#">10 Comments</a></li>
                                        </ul>
                                        <p>{{ article.Body }}</p>
                                        <div class="post-options">
                                            <div class="row">
                                                <div class="col-6">
                                                    <ul class="post-tags">
                                                        {% if is_liked %}
                                                        <li><a href="{% url 'blog:like' article.slug article.id %}"><i style="font-size: 20px" class="fa fa-heart"></i></a>{{ article.likes.all.count }}</li>
                                                        {% else %}
                                                        <li><a href="{% url 'blog:like' article.slug article.id %}"><i style="font-size: 20px" class="fa fa-heart-o"></i></a>{{ article.likes.all.count }}</li>
                                                        {% endif %}

                                                    </ul>
                                                </div>
                                                <div class="col-6">
                                                    <ul class="post-share">
                                                        <li><i class="fa fa-share-alt"></i></li>
                                                        <li><a href="#">Facebook</a>,</li>
                                                        <li><a href="#"> Twitter</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="sidebar-item comments">
                                    <div class="sidebar-heading">
                                        <h2>4 comments</h2>
                                    </div>
                                    <div class="content">
                                        <ul>
                                            {% for comment in article.comments.all %}
                                                {% if comment.parents == None %}
                                                    <li>
                                                        <div class="author-thumb">
                                                            <img src="{% static "images/comment-author-01.jpg" %}"
                                                                 alt="">
                                                        </div>
                                                        <div class="right-content">
                                                            <h4>{{ comment.user }}<span>{{ comment.created }}</span>
                                                            </h4>
                                                            <p>{{ comment.body }}</p>
                                                        </div>
                                                    </li>

                                                    {% for reply in comment.replies.all %}
                                                        <li class="replied">
                                                            <div class="author-thumb">
                                                                <img src="{% static "images/comment-author-02.jpg" %}"
                                                                     alt="">
                                                            </div>
                                                            <div class="right-content">
                                                                <h4>{{ reply.user }}<span>{{ reply.created }}</span>
                                                                </h4>
                                                                <p>{{ reply.body }}</p>
                                                            </div>
                                                        </li>
                                                    {% endfor %}
                                                {% endif %}
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="sidebar-item submit-comment">
                                    <div class="sidebar-heading">
                                        <h2>Your comment</h2>
                                    </div>
                                    <div class="content">
                                        <form id="comment" action="#" method="post">
                                            <div class="row">
                                                <div class="col-md-6 col-sm-12">
                                                    <fieldset>
                                                        <input name="name" type="text" id="name" placeholder="Your name"
                                                               required="">
                                                    </fieldset>
                                                </div>
                                                <div class="col-md-6 col-sm-12">
                                                    <fieldset>
                                                        <input name="email" type="text" id="email"
                                                               placeholder="Your email" required="">
                                                    </fieldset>
                                                </div>
                                                <div class="col-md-12 col-sm-12">
                                                    <fieldset>
                                                        <input name="subject" type="text" id="subject"
                                                               placeholder="Subject">
                                                    </fieldset>
                                                </div>
                                                <div class="col-lg-12">
                                                    <fieldset>
                                                        <textarea name="message" rows="6" id="message"
                                                                  placeholder="Type your comment"
                                                                  required=""></textarea>
                                                    </fieldset>
                                                </div>
                                                <div class="col-lg-12">
                                                    <fieldset>
                                                        <button type="submit" id="form-submit" class="main-button">
                                                            Submit
                                                        </button>
                                                    </fieldset>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% include 'includes/sidebar.html' %}
            </div>
        </div>
    </section>

{% endblock %}

blog/templates/blog/article_list.html
{% extends 'base.html' %}

{% block content %}

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
        <section class="page-heading">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-content">
                            <h4>Recent Posts</h4>
                            <h2>Our Recent Blog Entries</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Banner Ends Here -->




    <section class="blog-posts grid-system">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="all-blog-posts">
                        <div class="row">

                            {% for article in article_list %}
                                <div class="col-lg-6">
                                    <div class="blog-post">
                                        <div class="blog-thumb">
                                            <img src="{{ article.Image.url }}" alt="">
                                        </div>
                                        <div class="down-content">
                                            <span>{{ article.category.first }}</span>
                                            <a href="{% url "blog:article_detail" article.slug %}"><h4>{{ article.Title }}</h4></a>
                                            <ul class="post-info">
                                                <li><a href="#">{{ article.Author }}</a></li>
                                                <li><a href="#">{{ article.pub_date }}</a></li>
                                                <li><a href="#">26 Comments</a></li>
                                            </ul>
                                            <p>{{ article.Body }}</p>
                                            <div class="post-options">
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <ul class="post-tags">
                                                            <li><i class="fa fa-tags"></i></li>
                                                            <li><a href="#">Best Templates</a>,</li>
                                                            <li><a href="#">TemplateMo</a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}

                            {% if article_list.has_other_pages %}
                                <div class="col-lg-12">
                                    <ul class="page-numbers">
                                        {% if article_list.has_previous %}
                                            <li><a href="?page={{ article_list.previous_page_number }}{% if request.Get.q %}&q={{ request.Get.q }}{% endif %}"><i class="fa fa-angle-double-left"></i></a></li>
                                        {% endif %}



                                        {% for i in article_list.paginator.page_range %}
                                            {% if article_list.number == i %}
                                                <li class="active"><a href="?page={{ i }}{% if request.Get.q %}&q={{ request.Get.q }}{% endif %}">{{ i }}</a></li>
                                            {% else %}
                                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                                            {% endif %}
                                        {% endfor %}



                                        {% if article_list.has_next %}
                                            <li><a href="?page={{ article_list.next_page_number }}{% if request.Get.q %}&q={{ request.Get.q }}{% endif %}"><i class="fa fa-angle-double-right"></i></a></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% include 'includes/sidebar.html' %}
            </div>
        </div>
    </section>
{% endblock %}

    